- hosts: machine
  become: yes
  # become_method: sudo
  become_user: "{{ become_user }}"
  # gather_facts: false
  # pre_tasks:
  #   - include_tasks: tasks/dotfiles.yaml
  roles:
    - { role: zsh, tags: 'zsh' }
  #   - { role: bombsquad, tags: 'bombsquad' }
  #   - { role: kind-cluster, tags: 'kind-cluster' }
  # tags: [ 'never' ]
